#!/bin/bash
printf "===START dns.google.com===\n"
curl -k -H "accept: application/dns-json" "https://dns.google.com/resolve?name=hackingyseguridad.com&type=AAAA"
printf "\n===END dns.google.com===\n"
printf "===START cloudflare-dns.com===\n"
curl -k -H "accept: application/dns-json" "https://cloudflare-dns.com/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END cloudflare-dns.com===\n"
printf "===START 1.1.1.1===\n"
curl -k -H "accept: application/dns-json" "https://1.1.1.1/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END 1.1.1.1===\n"
printf "===START dns9.quad9.net===\n"
curl -k -H "accept: application/dns-json" "https://dns9.quad9.net/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END dns9.quad9.net===\n"
printf "===START dns10.quad9.net===\n"
curl -k -H "accept: application/dns-json" "https://dns10.quad9.net/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END dns10.quad9.net===\n"
printf "===START dns.quad9.net===\n"
curl -k -H "accept: application/dns-json" "https://dns.quad9.net/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END dns.quad9.net===\n"
printf "===START doh.cleanbrowsing.org===\n"
curl -k -H "accept: application/dns-json" "https://doh.cleanbrowsing.org/doh/family-filter/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.cleanbrowsing.org===\n"
printf "===START dns.dnsoverhttps.net===\n"
curl -k -H "accept: application/dns-json" "https://dns.dnsoverhttps.net/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END dns.dnsoverhttps.net===\n"
printf "===START doh.crypto.sx===\n"
curl -k -H "accept: application/dns-json" "https://doh.crypto.sx/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.crypto.sx===\n"
printf "===START doh.powerdns.org===\n"
curl -k -H "accept: application/dns-json" "https://doh.powerdns.org/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.powerdns.org===\n"
printf "===START doh.securedns.eu===\n"
curl -k -H "accept: application/dns-json" "https://doh.securedns.eu/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.securedns.eu===\n"
printf "===START doh.ibr.cs.tu-bs.de===\n"
curl -k -H "accept: application/dns-json" "https://doh.ibr.cs.tu-bs.de/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.ibr.cs.tu-bs.de===\n"
printf "===START doh.eieidns.com===\n"
curl -k -H "accept: application/dns-json" "https://doh.eieidns.com/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.eieidns.com===\n"
printf "===START doh.blahdns.com===\n"
curl -k -H "accept: application/dns-json" "https://doh.blahdns.com/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.blahdns.com===\n"
printf "===START doh.de.blahdns.com===\n"
curl -k -H "accept: application/dns-json" "https://doh.de.blahdns.com/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.de.blahdns.com===\n"
printf "===START doh.defaultroutes.de===\n"
curl -k -H "accept: application/dns-json" "https://doh.defaultroutes.de/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.defaultroutes.de===\n"
printf "===START doh.bugdns.com===\n"
curl -k -H "accept: application/dns-json" "https://doh.bugdns.com/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.bugdns.com===\n"
printf "===START doh.datt.pw===\n"
curl -k -H "accept: application/dns-json" "https://doh.datt.pw/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.datt.pw===\n"
printf "===START doh.ntu.ssooss.win===\n"
curl -k -H "accept: application/dns-json" "https://doh.ntu.ssooss.win/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.ntu.ssooss.win===\n"
printf "===START dns.dnsoverhttps.net===\n"
curl -k -H "accept: application/dns-json" "https://dns.dnsoverhttps.net/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END dns.dnsoverhttps.net===\n"
printf "===START dns.dns-over-https.com===\n"
curl -k -H "accept: application/dns-json" "https://dns.dns-over-https.com/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END dns.dns-over-https.com===\n"
printf "===START dns.rubyfish.cn===\n"
curl -k -H "accept: application/dns-json" "https://dns.rubyfish.cn/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END dns.rubyfish.cn===\n"
printf "===START doh.qis.io===\n"
curl -k -H "accept: application/dns-json" "https://doh.qis.io/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END doh.qis.io===\n"
printf "===START public.dns.iij.jp===\n"
curl -k -H "accept: application/dns-json" "https://public.dns.iij.jp/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END public.dns.iij.jp===\n"
printf "===START dns.nextdns.io===\n"
curl -k -H "accept: application/dns-json" "https://dns.nextdns.io/dns-query?name=hackingyseguridad.com&type=AAAA"
printf "\n===END dns.nextdns.io ===\n"
